version: '3.9'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: proyecto_tienda_virtual
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistir datos
    networks:
      - app_network

  # API Spring Boot
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_api
    ports:
      - "8080:8080"
    environment:
      # Conexión a BD usando nombre del servicio
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/proyecto_tienda_virtual
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

      # Variables de entorno externas
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
    depends_on:
      - postgres  # Esperar a que postgres esté listo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: