spring.application.name=proyecto
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_tienda_virtual
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de Hibernate (JPA)
# create-drop
# update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Configuración de Spring Security
spring.security.user.name=user
spring.security.user.password=password

#jwt
app.jwt.secret=3aafe6b6efa7d54ea39fc84539dbccb4ffc2969127d006798cec33ffede337c1
app.jwt.expiration=86400000
app.jwt.header=Authorization
app.jwt.prefix=Bearer
app.jwt.user=admin

# Configuración de subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# cloudinary
cloudinary.url=${CLOUDINARY_URL}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# configuracion de spring ai
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${OPENAI_BASE_URL}
spring.ai.openai.model=${OPENAI_MODEL}
