spring.application.name=proyecto


# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_tienda_virtual
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de Hibernate (JPA)
# create-drop
# update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Configuración de Spring Security
spring.security.user.name=user
spring.security.user.password=password

#jwt
app.jwt.secret=3aafe6b6efa7d54ea39fc84539dbccb4ffc2969127d006798cec33ffede337c1
app.jwt.expiration=86400000
app.jwt.header=Authorization
app.jwt.prefix=Bearer
app.jwt.user=admin

# Configuración de subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# cloudinary
cloudinary.url=
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html